### ISSUE TITLE
Unable to use FROM_UNIXTIME function

### ISSUE THREAD

**Issue by anarcist69** [nilportugues/sql-query-builder#69]
Writing code like so:

    $builder = new MySqlBuilder();

    $query = $builder->select()
                ->setTable('invoices');

    $columns['Invoice Number'] = 'invoice_number'; //Always Display
    $query->setColumns($columns);
    $query->setFunctionAsColumn('FROM_UNIXTIME', array('invoices.invoice_date', '%d/%m/%Y'), 'Date Entered');
    $builder->write($query);

And it is returning MySQL that is invalid:

    SELECT `invoices`.`invoice_number` AS `Invoice Number`, ``.`FROM_UNIXTIME(invoices.invoice_date, %d/%m/%Y)` AS `Date Entered` FROM `invoices`

**Comment by nilopc** [comment]
@anarcist69 it is indeed a bug, as the GenericBuilder is outputting the expected query. 

I'll look into it today. It shouldn't be too hard to fix. 

Thanks for reporting, I'll keep you posted

**Comment by nilopc** [comment]
Fixed it. https://github.com/nilportugues/sql-query-builder/commit/3dca30b0eaee835783fa61286a51dda425cd3838

Use release 1.2.1 :+1:

**Comment by anarcist69** [comment]
Thanks, almost got it. Looks like it still isn't outputting quite right.

MySQL requires formatting like this:

    FROM_UNIXTIME(invoices.invoice_date, "%d/%m/%Y")

output is like this (Note the spaces after % signs and no quotation marks surrounding the second argument):

    FROM_UNIXTIME(invoices.invoice_date, % d /% m /% Y)

Thanks for responding so fast.

**Comment by changetip** [comment]
Hi @nilopc, @anarcist69 sent you a tip worth 1 coffee (4,060 bits/$1.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/925126)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
